import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import AuthBar from "../components/AuthBar";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const session = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <AuthBar status={session.status} />
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Welcome to <span className="text-purple-300">Linker</span>{" "}
          {session.data?.user?.name}
        </h1>
      </main>
    </>
  );
};

export default Home;
