import Head from "next/head";

const EditLinkerPage = () => {
  return (
    <>
      <Head>
        <title>Edit Linker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Edit</h1>
    </>
  );
};

export default EditLinkerPage;
